server:
  port: 8081

spring:
  application:
    name: notification-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.example.notification: DEBUG

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

ipera:
  event-service:
    url: http://event-service/save-event